# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19src/proto/inference.proto\"!\n\x10InferenceRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\'\n\x11InferenceResponse\x12\x12\n\nprediction\x18\x01 \x01(\t2\x81\x01\n\x10InferenceService\x12\x30\n\x05infer\x12\x11.InferenceRequest\x1a\x12.InferenceResponse\"\x00\x12;\n\x0cinfer_stream\x12\x11.InferenceRequest\x1a\x12.InferenceResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERENCEREQUEST._serialized_start=29
  _INFERENCEREQUEST._serialized_end=62
  _INFERENCERESPONSE._serialized_start=64
  _INFERENCERESPONSE._serialized_end=103
  _INFERENCESERVICE._serialized_start=106
  _INFERENCESERVICE._serialized_end=235
# @@protoc_insertion_point(module_scope)
