# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.proto import inference_pb2 as src_dot_proto_dot_inference__pb2


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.infer = channel.unary_unary(
                '/InferenceService/infer',
                request_serializer=src_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
                )
        self.infer_stream = channel.stream_stream(
                '/InferenceService/infer_stream',
                request_serializer=src_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
                )


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def infer_stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'infer': grpc.unary_unary_rpc_method_handler(
                    servicer.infer,
                    request_deserializer=src_dot_proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=src_dot_proto_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
            'infer_stream': grpc.stream_stream_rpc_method_handler(
                    servicer.infer_stream,
                    request_deserializer=src_dot_proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=src_dot_proto_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InferenceService/infer',
            src_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            src_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def infer_stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/InferenceService/infer_stream',
            src_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            src_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
